id: P94245490
initial_creation_type: input
source_metadata:
  title: Nubchen Sangye Yeshe
  language: en
  description: 'Texts by and about Nubchen Sangye Yeshe (gnubs chen sangs rgyas ye
    shes), a major figure in the early Nyingma lineage:'
  volume:
    57cf67b438cd4ae3a2753da1eadd17dd:
      title: Restorative Offering to the Eight Classes
      parent: Dharma Protectors
created_at: '2022-03-01T01:02:29.671426'
last_modified_at: '2022-03-01T01:02:29.671432'
